name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

jobs:
  vim-tests:
    name: Vim unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['7.4', '8.0']
    steps:
      - uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-20.09
      - name: Install Cachix
        uses: cachix/cachix-action@v9
        with:
          name: whonore-vim
          skipPush: true
      - name: Install Vim ${{ matrix.version }}
        run: nix-env -j auto -i -f ci/vim.nix --argstr version ${{ matrix.version }}
      - name: Install Vader
        uses: actions/checkout@v2
        with:
          repository: junegunn/vader.vim
          path: ./vader.vim
      - name: Run Vim tests
        env:
          VADER_PATH: $GITHUB_WORKSPACE/vader.vim
        working-directory: ./tests/vim
        run: ./run.sh
